image: gitpod/workspace-dotnet

tasks:
  - name: Frontend
    init: |
      cd src/Website
      npm ci
      API_URL=$(gp url 8080)
      sed -i -e "s|http://localhost:8080|${API_URL}|g" src/environments/environment.ts
    command: |
      gp url 4200
      npm run start

  - name: Backend
    init: |
      echo "Downloading and installing .NET 7 SDK for .NET tools"
      curl https://download.visualstudio.microsoft.com/download/pr/5202b091-2406-445c-b40a-68a5b97c882b/b509f2a7a0eb61aea145b990b40b6d5b/dotnet-sdk-7.0.405-linux-x64.tar.gz --output sdk.tar.gz
      tar --skip-old-files -zxf sdk.tar.gz -C /home/gitpod/dotnet
      dotnet tool restore
      cd src/WebApi
    command: |
      gp url 8080
      dotnet watch run
    openMode: split-right

ports:
  - port: 4200
    onOpen: open-browser
    visibility: public
  - port: 8080
    visibility: public
