image: gitpod/workspace-dotnet

tasks:
    - name: Frontend
      init: |
          cd src/Website
          npm ci --legacy-peer-deps
          npm run build:dev
          gp sync-done frontend
      command: |
          gp url 5000
          npm run watch

    - name: Backend
      init: |
          dotnet restore
          cd src/WebApi
          dotnet build
          gp sync-await frontend
      command: |
          gp url 6000
          sleep 60
          dotnet watch run
      openMode: split-right

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
