image: gitpod/workspace-dotnet

tasks:
  - name: Frontend
    init: |
      cd src/Website
      npm ci
    command: |
      gp url 4200
      npm run start

  - name: Backend
    init: |
      curl https://download.visualstudio.microsoft.com/download/pr/01292c7c-a1ec-4957-90fc-3f6a2a1e5edc/025e84c4d9bd4aeb003d4f07b42e9159/dotnet-sdk-6.0.418-linux-x64.tar.gz --output sdk.tar.gz
      tar --skip-old-files -zxf sdk.tar.gz -C /home/gitpod/dotnet
      dotnet tool restore
      cd src/WebApi
    command: |
      gp url 8080
      dotnet watch run
    openMode: split-right

ports:
  - port: 4200
    onOpen: open-browser
    visibility: public
  - port: 8080
    visibility: public
