/**
 * OpenSpace.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Slot } from './slot';
import { Topic } from './topic';
import { Room } from './room';


export interface Session { 
    id: number;
    name: string;
    createdAt: string;
    rooms: Array<Room>;
    slots: Array<Slot>;
    topics: Array<Topic>;
    votingEnabled: boolean;
    freeForAll: boolean;
    attendanceEnabled: boolean;
    teamsAnnouncementsEnabled: boolean;
}

